package com.jzt.system.bean;

public class Drug_Warehouse {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_warehouse.id
     *
     * @mbg.generated Tue Sep 17 17:33:38 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_warehouse.name
     *
     * @mbg.generated Tue Sep 17 17:33:38 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_warehouse.norms
     *
     * @mbg.generated Tue Sep 17 17:33:38 CST 2019
     */
    private String norms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_warehouse.price
     *
     * @mbg.generated Tue Sep 17 17:33:38 CST 2019
     */
    private String price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_warehouse.firm
     *
     * @mbg.generated Tue Sep 17 17:33:38 CST 2019
     */
    private String firm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_warehouse.category
     *
     * @mbg.generated Tue Sep 17 17:33:38 CST 2019
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_warehouse.count
     *
     * @mbg.generated Tue Sep 17 17:33:38 CST 2019
     */
    private Long count;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_warehouse.id
     *
     * @return the value of drug_warehouse.id
     *
     * @mbg.generated Tue Sep 17 17:33:38 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_warehouse.id
     *
     * @param id the value for drug_warehouse.id
     *
     * @mbg.generated Tue Sep 17 17:33:38 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_warehouse.name
     *
     * @return the value of drug_warehouse.name
     *
     * @mbg.generated Tue Sep 17 17:33:38 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_warehouse.name
     *
     * @param name the value for drug_warehouse.name
     *
     * @mbg.generated Tue Sep 17 17:33:38 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_warehouse.norms
     *
     * @return the value of drug_warehouse.norms
     *
     * @mbg.generated Tue Sep 17 17:33:38 CST 2019
     */
    public String getNorms() {
        return norms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_warehouse.norms
     *
     * @param norms the value for drug_warehouse.norms
     *
     * @mbg.generated Tue Sep 17 17:33:38 CST 2019
     */
    public void setNorms(String norms) {
        this.norms = norms == null ? null : norms.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_warehouse.price
     *
     * @return the value of drug_warehouse.price
     *
     * @mbg.generated Tue Sep 17 17:33:38 CST 2019
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_warehouse.price
     *
     * @param price the value for drug_warehouse.price
     *
     * @mbg.generated Tue Sep 17 17:33:38 CST 2019
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_warehouse.firm
     *
     * @return the value of drug_warehouse.firm
     *
     * @mbg.generated Tue Sep 17 17:33:38 CST 2019
     */
    public String getFirm() {
        return firm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_warehouse.firm
     *
     * @param firm the value for drug_warehouse.firm
     *
     * @mbg.generated Tue Sep 17 17:33:38 CST 2019
     */
    public void setFirm(String firm) {
        this.firm = firm == null ? null : firm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_warehouse.category
     *
     * @return the value of drug_warehouse.category
     *
     * @mbg.generated Tue Sep 17 17:33:38 CST 2019
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_warehouse.category
     *
     * @param category the value for drug_warehouse.category
     *
     * @mbg.generated Tue Sep 17 17:33:38 CST 2019
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_warehouse.count
     *
     * @return the value of drug_warehouse.count
     *
     * @mbg.generated Tue Sep 17 17:33:38 CST 2019
     */
    public Long getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_warehouse.count
     *
     * @param count the value for drug_warehouse.count
     *
     * @mbg.generated Tue Sep 17 17:33:38 CST 2019
     */
    public void setCount(Long count) {
        this.count = count;
    }
}