package com.jzt.system.bean;

public class Drug_Message {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_message.id
     *
     * @mbg.generated Sun Oct 20 22:59:27 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_message.name
     *
     * @mbg.generated Sun Oct 20 22:59:27 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_message.norms
     *
     * @mbg.generated Sun Oct 20 22:59:27 CST 2019
     */
    private String norms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_message.price
     *
     * @mbg.generated Sun Oct 20 22:59:27 CST 2019
     */
    private String price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_message.firm
     *
     * @mbg.generated Sun Oct 20 22:59:27 CST 2019
     */
    private String firm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_message.category
     *
     * @mbg.generated Sun Oct 20 22:59:27 CST 2019
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_message.cardID
     *
     * @mbg.generated Sun Oct 20 22:59:27 CST 2019
     */
    private String cardid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_message.id
     *
     * @return the value of drug_message.id
     *
     * @mbg.generated Sun Oct 20 22:59:27 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_message.id
     *
     * @param id the value for drug_message.id
     *
     * @mbg.generated Sun Oct 20 22:59:27 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_message.name
     *
     * @return the value of drug_message.name
     *
     * @mbg.generated Sun Oct 20 22:59:27 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_message.name
     *
     * @param name the value for drug_message.name
     *
     * @mbg.generated Sun Oct 20 22:59:27 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_message.norms
     *
     * @return the value of drug_message.norms
     *
     * @mbg.generated Sun Oct 20 22:59:27 CST 2019
     */
    public String getNorms() {
        return norms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_message.norms
     *
     * @param norms the value for drug_message.norms
     *
     * @mbg.generated Sun Oct 20 22:59:27 CST 2019
     */
    public void setNorms(String norms) {
        this.norms = norms == null ? null : norms.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_message.price
     *
     * @return the value of drug_message.price
     *
     * @mbg.generated Sun Oct 20 22:59:27 CST 2019
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_message.price
     *
     * @param price the value for drug_message.price
     *
     * @mbg.generated Sun Oct 20 22:59:27 CST 2019
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_message.firm
     *
     * @return the value of drug_message.firm
     *
     * @mbg.generated Sun Oct 20 22:59:27 CST 2019
     */
    public String getFirm() {
        return firm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_message.firm
     *
     * @param firm the value for drug_message.firm
     *
     * @mbg.generated Sun Oct 20 22:59:27 CST 2019
     */
    public void setFirm(String firm) {
        this.firm = firm == null ? null : firm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_message.category
     *
     * @return the value of drug_message.category
     *
     * @mbg.generated Sun Oct 20 22:59:27 CST 2019
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_message.category
     *
     * @param category the value for drug_message.category
     *
     * @mbg.generated Sun Oct 20 22:59:27 CST 2019
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_message.cardID
     *
     * @return the value of drug_message.cardID
     *
     * @mbg.generated Sun Oct 20 22:59:27 CST 2019
     */
    public String getCardid() {
        return cardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_message.cardID
     *
     * @param cardid the value for drug_message.cardID
     *
     * @mbg.generated Sun Oct 20 22:59:27 CST 2019
     */
    public void setCardid(String cardid) {
        this.cardid = cardid == null ? null : cardid.trim();
    }
}