package com.jzt.system.bean;

public class Warehouse {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.id
     *
     * @mbg.generated Thu Jun 20 20:19:12 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.name
     *
     * @mbg.generated Thu Jun 20 20:19:12 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.amount
     *
     * @mbg.generated Thu Jun 20 20:19:12 CST 2019
     */
    private String amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.date
     *
     * @mbg.generated Thu Jun 20 20:19:12 CST 2019
     */
    private String date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.price
     *
     * @mbg.generated Thu Jun 20 20:19:12 CST 2019
     */
    private String price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.acceptor
     *
     * @mbg.generated Thu Jun 20 20:19:12 CST 2019
     */
    private String acceptor;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.id
     *
     * @return the value of warehouse.id
     *
     * @mbg.generated Thu Jun 20 20:19:12 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.id
     *
     * @param id the value for warehouse.id
     *
     * @mbg.generated Thu Jun 20 20:19:12 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.name
     *
     * @return the value of warehouse.name
     *
     * @mbg.generated Thu Jun 20 20:19:12 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.name
     *
     * @param name the value for warehouse.name
     *
     * @mbg.generated Thu Jun 20 20:19:12 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.amount
     *
     * @return the value of warehouse.amount
     *
     * @mbg.generated Thu Jun 20 20:19:12 CST 2019
     */
    public String getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.amount
     *
     * @param amount the value for warehouse.amount
     *
     * @mbg.generated Thu Jun 20 20:19:12 CST 2019
     */
    public void setAmount(String amount) {
        this.amount = amount == null ? null : amount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.date
     *
     * @return the value of warehouse.date
     *
     * @mbg.generated Thu Jun 20 20:19:12 CST 2019
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.date
     *
     * @param date the value for warehouse.date
     *
     * @mbg.generated Thu Jun 20 20:19:12 CST 2019
     */
    public void setDate(String date) {
        this.date = date == null ? null : date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.price
     *
     * @return the value of warehouse.price
     *
     * @mbg.generated Thu Jun 20 20:19:12 CST 2019
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.price
     *
     * @param price the value for warehouse.price
     *
     * @mbg.generated Thu Jun 20 20:19:12 CST 2019
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.acceptor
     *
     * @return the value of warehouse.acceptor
     *
     * @mbg.generated Thu Jun 20 20:19:12 CST 2019
     */
    public String getAcceptor() {
        return acceptor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.acceptor
     *
     * @param acceptor the value for warehouse.acceptor
     *
     * @mbg.generated Thu Jun 20 20:19:12 CST 2019
     */
    public void setAcceptor(String acceptor) {
        this.acceptor = acceptor == null ? null : acceptor.trim();
    }
}