package com.jzt.system.mapper;

import com.jzt.system.bean.Drug;
import com.jzt.system.bean.DrugExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DrugMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug
     *
     * @mbg.generated Tue Sep 17 17:33:38 CST 2019
     */
    long countByExample(DrugExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug
     *
     * @mbg.generated Tue Sep 17 17:33:38 CST 2019
     */
    int deleteByExample(DrugExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug
     *
     * @mbg.generated Tue Sep 17 17:33:38 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug
     *
     * @mbg.generated Tue Sep 17 17:33:38 CST 2019
     */
    int insert(Drug record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug
     *
     * @mbg.generated Tue Sep 17 17:33:38 CST 2019
     */
    int insertSelective(Drug record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug
     *
     * @mbg.generated Tue Sep 17 17:33:38 CST 2019
     */
    List<Drug> selectByExample(DrugExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug
     *
     * @mbg.generated Tue Sep 17 17:33:38 CST 2019
     */
    Drug selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug
     *
     * @mbg.generated Tue Sep 17 17:33:38 CST 2019
     */
    int updateByExampleSelective(@Param("record") Drug record, @Param("example") DrugExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug
     *
     * @mbg.generated Tue Sep 17 17:33:38 CST 2019
     */
    int updateByExample(@Param("record") Drug record, @Param("example") DrugExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug
     *
     * @mbg.generated Tue Sep 17 17:33:38 CST 2019
     */
    int updateByPrimaryKeySelective(Drug record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug
     *
     * @mbg.generated Tue Sep 17 17:33:38 CST 2019
     */
    int updateByPrimaryKey(Drug record);


    void inserts(List<Drug> list);

    void updateById(Drug record);

    void insertsOut(List<Drug> list);

    void updateByIdOut(Drug record);

}