package com.jzt.system.mapper;

import com.jzt.system.bean.Drug_Message;
import com.jzt.system.bean.Drug_MessageExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface Drug_MessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_message
     *
     * @mbg.generated Sun Oct 20 22:59:27 CST 2019
     */
    long countByExample(Drug_MessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_message
     *
     * @mbg.generated Sun Oct 20 22:59:27 CST 2019
     */
    int deleteByExample(Drug_MessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_message
     *
     * @mbg.generated Sun Oct 20 22:59:27 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_message
     *
     * @mbg.generated Sun Oct 20 22:59:27 CST 2019
     */
    int insert(Drug_Message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_message
     *
     * @mbg.generated Sun Oct 20 22:59:27 CST 2019
     */
    int insertSelective(Drug_Message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_message
     *
     * @mbg.generated Sun Oct 20 22:59:27 CST 2019
     */
    List<Drug_Message> selectByExample(Drug_MessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_message
     *
     * @mbg.generated Sun Oct 20 22:59:27 CST 2019
     */
    Drug_Message selectByPrimaryKey(Long id);

    Drug_Message selectAllBycardID(String cardID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_message
     *
     * @mbg.generated Sun Oct 20 22:59:27 CST 2019
     */
    int updateByExampleSelective(@Param("record") Drug_Message record, @Param("example") Drug_MessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_message
     *
     * @mbg.generated Sun Oct 20 22:59:27 CST 2019
     */
    int updateByExample(@Param("record") Drug_Message record, @Param("example") Drug_MessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_message
     *
     * @mbg.generated Sun Oct 20 22:59:27 CST 2019
     */
    int updateByPrimaryKeySelective(Drug_Message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_message
     *
     * @mbg.generated Sun Oct 20 22:59:27 CST 2019
     */
    int updateByPrimaryKey(Drug_Message record);

    Drug_Message selectDMByCardid(String cardid);
    void inserts(List<Drug_Message> list);
    void updateById(Drug_Message record);
}