package com.jzt.system.mapper;

import com.jzt.system.bean.Drug_OutWarehouse;
import com.jzt.system.bean.Drug_OutWarehouseExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface Drug_OutWarehouseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_outwarehouse
     *
     * @mbg.generated Tue Oct 08 20:38:04 CST 2019
     */
    long countByExample(Drug_OutWarehouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_outwarehouse
     *
     * @mbg.generated Tue Oct 08 20:38:04 CST 2019
     */
    int deleteByExample(Drug_OutWarehouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_outwarehouse
     *
     * @mbg.generated Tue Oct 08 20:38:04 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_outwarehouse
     *
     * @mbg.generated Tue Oct 08 20:38:04 CST 2019
     */
    int insert(Drug_OutWarehouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_outwarehouse
     *
     * @mbg.generated Tue Oct 08 20:38:04 CST 2019
     */
    int insertSelective(Drug_OutWarehouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_outwarehouse
     *
     * @mbg.generated Tue Oct 08 20:38:04 CST 2019
     */
    List<Drug_OutWarehouse> selectByExample(Drug_OutWarehouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_outwarehouse
     *
     * @mbg.generated Tue Oct 08 20:38:04 CST 2019
     */
     Drug_OutWarehouse selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_outwarehouse
     *
     * @mbg.generated Tue Oct 08 20:38:04 CST 2019
     */
    int updateByExampleSelective(@Param("record") Drug_OutWarehouse record, @Param("example") Drug_OutWarehouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_outwarehouse
     *
     * @mbg.generated Tue Oct 08 20:38:04 CST 2019
     */
    int updateByExample(@Param("record") Drug_OutWarehouse record, @Param("example") Drug_OutWarehouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_outwarehouse
     *
     * @mbg.generated Tue Oct 08 20:38:04 CST 2019
     */
    int updateByPrimaryKeySelective(Drug_OutWarehouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_outwarehouse
     *
     * @mbg.generated Tue Oct 08 20:38:04 CST 2019
     */
    int updateByPrimaryKey(Drug_OutWarehouse record);

    void inserts(List<Drug_OutWarehouse> list);

    void updateById(Drug_OutWarehouse record);
}